USE [master]
GO

/****** Object:  Database [rsu_library_system]    Script Date: 08/03/2020 8:46:02 PM ******/
CREATE DATABASE [rsu_library_system]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'rsu_library_system', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\rsu_library_system.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'rsu_library_system_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\rsu_library_system_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [rsu_library_system] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [rsu_library_system].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [rsu_library_system] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [rsu_library_system] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [rsu_library_system] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [rsu_library_system] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [rsu_library_system] SET ARITHABORT OFF 
GO

ALTER DATABASE [rsu_library_system] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [rsu_library_system] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [rsu_library_system] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [rsu_library_system] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [rsu_library_system] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [rsu_library_system] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [rsu_library_system] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [rsu_library_system] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [rsu_library_system] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [rsu_library_system] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [rsu_library_system] SET  DISABLE_BROKER 
GO

ALTER DATABASE [rsu_library_system] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [rsu_library_system] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [rsu_library_system] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [rsu_library_system] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [rsu_library_system] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [rsu_library_system] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [rsu_library_system] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [rsu_library_system] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [rsu_library_system] SET  MULTI_USER 
GO

ALTER DATABASE [rsu_library_system] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [rsu_library_system] SET DB_CHAINING OFF 
GO

ALTER DATABASE [rsu_library_system] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [rsu_library_system] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [rsu_library_system] SET  READ_WRITE 
GO

